// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiuatV1oPrgMh5oLlhwsp7hiaYb7nbQ0Q',
    appId: '1:245238143714:web:e11b855efd6c4e495e9cbb',
    messagingSenderId: '245238143714',
    projectId: 'message-notifier-dca31',
    authDomain: 'message-notifier-dca31.firebaseapp.com',
    storageBucket: 'message-notifier-dca31.appspot.com',
    measurementId: 'G-KG395JNKKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLGnumeYB-d5PbWVfIADR0rd7PHD5A7rk',
    appId: '1:245238143714:android:5ae09d6e94b5d8055e9cbb',
    messagingSenderId: '245238143714',
    projectId: 'message-notifier-dca31',
    storageBucket: 'message-notifier-dca31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArFl7nqXRRK0crxbB2zLiolSfM8vRldyA',
    appId: '1:245238143714:ios:e2b8db49ecd4031e5e9cbb',
    messagingSenderId: '245238143714',
    projectId: 'message-notifier-dca31',
    storageBucket: 'message-notifier-dca31.appspot.com',
    iosBundleId: 'com.example.pakWheelsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArFl7nqXRRK0crxbB2zLiolSfM8vRldyA',
    appId: '1:245238143714:ios:e2b8db49ecd4031e5e9cbb',
    messagingSenderId: '245238143714',
    projectId: 'message-notifier-dca31',
    storageBucket: 'message-notifier-dca31.appspot.com',
    iosBundleId: 'com.example.pakWheelsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiuatV1oPrgMh5oLlhwsp7hiaYb7nbQ0Q',
    appId: '1:245238143714:web:e743302fb56651555e9cbb',
    messagingSenderId: '245238143714',
    projectId: 'message-notifier-dca31',
    authDomain: 'message-notifier-dca31.firebaseapp.com',
    storageBucket: 'message-notifier-dca31.appspot.com',
    measurementId: 'G-J5KMWGDY6M',
  );
}
